# Generated by Django 3.1.7 on 2022-04-04 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20220404_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostUser',
        ),
    ]
