# Generated by Django 3.1.7 on 2022-04-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
