# Generated by Django 3.1.7 on 2022-04-09 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
