# Generated by Django 3.1.7 on 2022-04-10 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20220410_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
    ]
